version: "3.8"

services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "10000:10000"
    environment:
      - LOCAL=1
    command: ["python", "__main__.py", "-api"]
