version: '3.8'

volumes:
  postgres_data:

services:
  db:
    container_name: db
    image: postgres:15.1-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file:
      - .env.dev
