version: "3.8"

volumes:
  postgres_data_atm_banking:

services:
#  web:
#    container_name: web
#    build:
#      context: .
#      dockerfile: Dockerfile.web
#    depends_on:
#      - db
#      - migrations
#    environment:
#      - LAUNCH=rem
#    env_file:
#      - .env.remote.template
#    restart: always
#    command: python atm -api

  web:
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile.web
    depends_on:
      - db
      - migrations
    environment:
      - LAUNCH=rem
    restart: always
    command: [
      "gunicorn", "atm.__runner_remote__:app",
      "--workers", "4", "--worker-class", "uvicorn.workers.UvicornWorker",
      "--bind", "0.0.0.0:10000"
    ]

  db:
    container_name: db
    image: postgres:16rc1-alpine3.18
    env_file:
      - .env.template
    restart: always
    volumes:
      - postgres_data_atm_banking:/var/lib/postgresql/data/

  migrations:
    container_name: migrations
    build:
      context: .
      dockerfile: Dockerfile.migrations
    depends_on:
      - db
    environment:
      - LAUNCH=rem
    restart: on-failure
    command: ["alembic", "upgrade", "head"]

  nginx:
    container_name: reverse_proxy
    image: nginx:1.25.3-alpine
    ports:
      - "18900:8080"
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
