version: "3.8"

volumes:
  postgres_data_atm_banking:
#  app_data_atm_banking:

services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: ./Dockerfile.main
    depends_on:
      - db
      - migrations
    ports:
      7000:7002
#    env_file:
#      - .env.dev
#    command: ["python", "__main__.py", "-api"]
    command: poetry run python __main__.py -api
#    command: ["poetry", "env", "info", "--path"]
#    command: ["python", "-m", "pip", "list"]

  db:
    container_name: db
    image: postgres:16rc1-alpine3.18
    restart: always
    volumes:
      - postgres_data_atm_banking:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file:
      - .env.dev

  migrations:
    container_name: migrations
    build:
      context: .
      dockerfile: ./Dockerfile.migrations
    depends_on:
      - db
    env_file:
      - .env.dev
    command: alembic upgrade head
#    command: which python
#    command: pwd
#    command: ["poetry", "env", "info", "--path"]
#    command: ["python", "-m", "pip", "list"]
