version: "3.8"

volumes:
  postgres_data_atm_banking:

services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile.web
    depends_on:
      - db
      - migrations
    environment:
      - LAUNCH=rem
    env_file:
      - .env.remote.template
    command: ["python", "runner.py", "-api"]

  db:
    container_name: db
    image: postgres:16rc1-alpine3.18
    restart: always
    volumes:
      - postgres_data_atm_banking:/var/lib/postgresql/data/
    env_file:
      - .env.remote.template

  migrations:
    container_name: migrations
    build:
      context: .
      dockerfile: Dockerfile.migrations
    depends_on:
      - db
    environment:
      - LAUNCH=rem
    command: ["alembic", "upgrade", "head"]

  nginx:
    container_name: reverse_proxy
    image: nginx:1.25.3-alpine
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
