[tool.poetry]
name = "atm-banking"
version = "0.1.0"
description = ""
authors = ["Shiiq <anjunatown@gmail.com>"]
readme = "README.md"
packages = [{include = "atm_banking"}]

[tool.poetry.dependencies]
python = "^3.11"
sqlalchemy = "^2.0.13"
alembic = "^1.10.3"
aiosqlite = "^0.18.0"
asyncpg = "^0.27.0"
pydantic = {extras = ["dotenv"], version = "^1.10.7"}
dependency-injector = "^4.41.0"
fastapi = "^0.98.0"
uvicorn = {extras = ["standard"], version = "^0.22.0"}


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
