"""init

Revision ID: 0d969ab9ac65
Revises: 
Create Date: 2023-05-05 16:38:34.102780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d969ab9ac65'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_account',
    sa.Column('deposit', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bank_account'))
    )
    op.create_table('bank_customer',
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('bank_account_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['bank_account_id'], ['bank_account.id'], name=op.f('fk_bank_customer_bank_account_id_bank_account')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bank_customer')),
    sa.UniqueConstraint('first_name', 'last_name', name=op.f('uq_bank_customer_first_name_last_name')),
    sa.UniqueConstraint('id', 'bank_account_id', name=op.f('uq_bank_customer_id_bank_account_id'))
    )
    op.create_table('bank_operation',
    sa.Column('bank_client', sa.Integer(), nullable=False),
    sa.Column('bank_account', sa.Integer(), nullable=False),
    sa.Column('bank_operation', sa.Enum('DEPOSIT', 'WITHDRAW', name='bankoperationstodb'), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['bank_account'], ['bank_account.id'], name=op.f('fk_bank_operation_bank_account_bank_account')),
    sa.ForeignKeyConstraint(['bank_client'], ['bank_customer.id'], name=op.f('fk_bank_operation_bank_client_bank_customer')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bank_operation'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bank_operation')
    op.drop_table('bank_customer')
    op.drop_table('bank_account')
    # ### end Alembic commands ###
